name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.RELEASE_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push multi-arch Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/quakejs-stats
        VERSION=${GITHUB_REF#refs/tags/}

        docker buildx create --use

        docker buildx build --platform linux/amd64,linux/arm64 \
          --tag $IMAGE_NAME:latest \
          --tag $IMAGE_NAME:$VERSION \
          --push \
          --file build/Dockerfile build
